engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  coffeelint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
