### Project specific config ###
language: generic

env:
  env:
  global:
    - APM_TEST_PACKAGES="linter"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os: linux

sudo: required

services:
  - docker

install:
  - git clone --depth 1 https://github.com/codeclimate/codeclimate.git
  - cd codeclimate && sudo make install && cd ..

before_script:
  - docker info
  - codeclimate version

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - libgconf-2-4
    - xvfb
    - libnss3-dev
